### ISSUE TITLE
I have a problem with your project esp does not work I see a black screen

### ISSUE THREAD

**Issue by krysjak** [g0ldyy/NameIt#13] opened 2024-03-09 15:45 UTC
I have a problem with your project esp does not work I see a black screen

**Comment by ImInTheICU** [comment] 2024-03-09 22:40
Already solved (duplicate of): https://github.com/g0ldyy/NameIt/issues/9, https://github.com/g0ldyy/NameIt/issues/2.

**Closed as completed** 2024-03-23 13:52 UTC
